#define             MAIN            1
#define             END             2
#define             READ            3
#define             ID              5
#define             ENTERO          6	
#define             LPAREN          7
#define             RPAREN          8
#define             SEMICOLON       9
#define             COMMA           10
#define             ASSIGNOP        11
#define             PLUSOP          12
#define             MINUSOP         13
#define             REALLIT         14
#define             COMENTARIO      15
#define             CADENACHAR      16
#define             INTER       	17
#define             MULTOP          18
#define             DIVOP           19
#define             VAR             20
#define             IF              21
#define             ELSE            22
#define             WHILE           23
#define             PRINT           24
#define             EXPRESION       25
#define             INT             26
#define             CONST           27
#define             COMILLAS		28
#define             ILLAVE			29
#define             DLLAVE			30
#define             DPOINTS			31

